export type PlanId = "basico" | "essencial" | "premium";

export interface Plan {
  id: PlanId;
  name: string;
  price: number;
  positioning: string;
  highlighted?: boolean;
  ctaLabel: string;
  featuresList: string[];
  footnote?: string;
  features: { label: string; value: string }[];
}

export const plans: Plan[] = [
  {
    id: "basico",
    name: "Básico",
    price: 1200,
    positioning: "Para sair da vulnerabilidade e manter sua operação em conformidade.",
    ctaLabel: "Quero sair da vulnerabilidade",
    featuresList: [
      "Visitas presenciais quinzenais",
      "Documentação ANVISA completa e POPs",
      "Checklist de inspeção sanitária",
      "Relatório simplificado de não conformidades",
      "Plano de ação para adequações",
      "Orientação sobre armazenamento e controle de validade",
      "Suporte via WhatsApp em horário comercial (seg-sex, 9h-18h)",
      "Atualização de documentos regulatórios quando necessário",
      "Apoio básico em fiscalizações sanitárias",
    ],
    footnote: "Manual de Boas Práticas e fichas técnicas disponíveis à parte.",
    features: [
      { label: "Visitas presenciais", value: "Quinzenais" },
      { label: "Nutricionista Responsável Técnico (RT)", value: "Não" },
      { label: "Documentação ANVISA e POPs", value: "Sim" },
      { label: "Manual de Boas Práticas", value: "À parte" },
      { label: "Checklist de inspeção sanitária", value: "Sim" },
      { label: "Relatório de não conformidades", value: "Simplificado" },
      { label: "Plano de ação para adequações", value: "Sim" },
      { label: "Auditoria interna mensal", value: "Não" },
      { label: "Revisão de cardápio", value: "Não" },
      { label: "Avaliação de desperdício alimentar", value: "Não" },
      { label: "Treinamento da equipe", value: "Não" },
      { label: "Simulação de fiscalização", value: "Não" },
      { label: "Criação de ficha técnica", value: "À parte" },
      { label: "Indicadores mensais de conformidade", value: "Não" },
      { label: "Análise de custos e cardápio", value: "Não" },
      { label: "Reuniões gerenciais", value: "Não" },
      { label: "WhatsApp com nutricionista", value: "Comercial (9h-18h)" },
      { label: "Apoio em fiscalizações", value: "Básico" },
    ],
  },
  {
    id: "essencial",
    name: "Essencial",
    price: 2300,
    positioning: "Para operar com confiança e passar qualquer fiscalização.",
    ctaLabel: "Quero parar de apagar incêndio",
    featuresList: [
      "Visitas presenciais semanais (1x por semana)",
      "Documentação ANVISA completa e POPs",
      "Manual de Boas Práticas padrão",
      "Auditoria interna mensal",
      "Relatório completo com plano de ação",
      "Revisão e adequação de registros obrigatórios",
      "Revisão periódica de cardápio",
      "Avaliação de desperdício alimentar",
      "Treinamento periódico da equipe",
      "Simulação de fiscalização sanitária",
      "Revisão de fornecedores e documentos obrigatórios",
      "WhatsApp com horário estendido (até 20h e sábados)",
    ],
    footnote: "Criação de fichas técnicas disponível à parte.",
    features: [
      { label: "Visitas presenciais", value: "1x/semana" },
      { label: "Nutricionista Responsável Técnico (RT)", value: "Não" },
      { label: "Documentação ANVISA e POPs", value: "Sim" },
      { label: "Manual de Boas Práticas", value: "Padrão" },
      { label: "Checklist de inspeção sanitária", value: "Sim" },
      { label: "Relatório de não conformidades", value: "Completo" },
      { label: "Plano de ação para adequações", value: "Sim" },
      { label: "Auditoria interna mensal", value: "Sim" },
      { label: "Revisão de cardápio", value: "Sim" },
      { label: "Avaliação de desperdício alimentar", value: "Sim" },
      { label: "Treinamento da equipe", value: "Periódico" },
      { label: "Simulação de fiscalização", value: "Sim" },
      { label: "Criação de ficha técnica", value: "À parte" },
      { label: "Indicadores mensais de conformidade", value: "Não" },
      { label: "Análise de custos e cardápio", value: "Não" },
      { label: "Reuniões gerenciais", value: "Não" },
      { label: "WhatsApp com nutricionista", value: "Estendido (até 20h e sáb)" },
      { label: "Apoio em fiscalizações", value: "Completo" },
    ],
  },
  {
    id: "premium",
    name: "Premium",
    price: 3400,
    positioning: "Um nutricionista atuando como parceiro estratégico do seu negócio.",
    highlighted: true,
    ctaLabel: "Quero um nutricionista no meu negócio",
    featuresList: [
      "Visitas presenciais 2x por semana",
      "Nutricionista Responsável Técnico (RT)",
      "Documentação ANVISA completa e POPs",
      "Manual de Boas Práticas personalizado para sua operação",
      "Criação e atualização de fichas técnicas",
      "Criação, análise e otimização de cardápios",
      "Controle e análise de desperdício alimentar",
      "Indicadores mensais de conformidade",
      "Análise de custos e rentabilidade do cardápio",
      "Treinamento mensal da equipe",
      "Reuniões gerenciais para acompanhamento de resultados",
      "Gestão e acompanhamento de planos de ação",
      "Apoio prioritário em fiscalizações e intercorrências",
      "WhatsApp prioritário com resposta em até 2 horas",
    ],
    footnote: "Possibilidade de estagiário contratado à parte.",
    features: [
      { label: "Visitas presenciais", value: "2x/semana" },
      { label: "Nutricionista Responsável Técnico (RT)", value: "Sim" },
      { label: "Documentação ANVISA e POPs", value: "Sim" },
      { label: "Manual de Boas Práticas", value: "Personalizado" },
      { label: "Checklist de inspeção sanitária", value: "Sim" },
      { label: "Relatório de não conformidades", value: "Completo" },
      { label: "Plano de ação para adequações", value: "Sim" },
      { label: "Auditoria interna mensal", value: "Sim" },
      { label: "Revisão de cardápio", value: "Sim" },
      { label: "Avaliação de desperdício alimentar", value: "Sim" },
      { label: "Treinamento da equipe", value: "Mensal" },
      { label: "Simulação de fiscalização", value: "Sim" },
      { label: "Criação de ficha técnica", value: "Sim" },
      { label: "Indicadores mensais de conformidade", value: "Sim" },
      { label: "Análise de custos e cardápio", value: "Sim" },
      { label: "Reuniões gerenciais", value: "Sim" },
      { label: "WhatsApp com nutricionista", value: "Prioritário (até 2h)" },
      { label: "Apoio em fiscalizações", value: "Prioritário" },
    ],
  },
];

export const planById = (id: PlanId): Plan =>
  plans.find((p) => p.id === id) as Plan;

export const comparisonRows = [
  "Visitas presenciais",
  "Nutricionista Responsável Técnico (RT)",
  "Documentação ANVISA e POPs",
  "Manual de Boas Práticas",
  "Checklist de inspeção sanitária",
  "Relatório de não conformidades",
  "Plano de ação para adequações",
  "Auditoria interna mensal",
  "Revisão de cardápio",
  "Avaliação de desperdício alimentar",
  "Treinamento da equipe",
  "Simulação de fiscalização",
  "Criação de ficha técnica",
  "Indicadores mensais de conformidade",
  "Análise de custos e cardápio",
  "Reuniões gerenciais",
  "WhatsApp com nutricionista",
  "Apoio em fiscalizações",
] as const;
